// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clients.proto

package contract

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterClientRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterClientRequest) Reset()         { *m = RegisterClientRequest{} }
func (m *RegisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterClientRequest) ProtoMessage()    {}
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{0}
}

func (m *RegisterClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientRequest.Unmarshal(m, b)
}
func (m *RegisterClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientRequest.Marshal(b, m, deterministic)
}
func (m *RegisterClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientRequest.Merge(m, src)
}
func (m *RegisterClientRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterClientRequest.Size(m)
}
func (m *RegisterClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientRequest proto.InternalMessageInfo

func (m *RegisterClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RegisterClientRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterClientResponse) Reset()         { *m = RegisterClientResponse{} }
func (m *RegisterClientResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterClientResponse) ProtoMessage()    {}
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{1}
}

func (m *RegisterClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientResponse.Unmarshal(m, b)
}
func (m *RegisterClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientResponse.Marshal(b, m, deterministic)
}
func (m *RegisterClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientResponse.Merge(m, src)
}
func (m *RegisterClientResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterClientResponse.Size(m)
}
func (m *RegisterClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientResponse proto.InternalMessageInfo

type LoginRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ValidateIDRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateIDRequest) Reset()         { *m = ValidateIDRequest{} }
func (m *ValidateIDRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateIDRequest) ProtoMessage()    {}
func (*ValidateIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{4}
}

func (m *ValidateIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateIDRequest.Unmarshal(m, b)
}
func (m *ValidateIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateIDRequest.Marshal(b, m, deterministic)
}
func (m *ValidateIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateIDRequest.Merge(m, src)
}
func (m *ValidateIDRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateIDRequest.Size(m)
}
func (m *ValidateIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateIDRequest proto.InternalMessageInfo

func (m *ValidateIDRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type ValidateIDResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateIDResponse) Reset()         { *m = ValidateIDResponse{} }
func (m *ValidateIDResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateIDResponse) ProtoMessage()    {}
func (*ValidateIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{5}
}

func (m *ValidateIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateIDResponse.Unmarshal(m, b)
}
func (m *ValidateIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateIDResponse.Marshal(b, m, deterministic)
}
func (m *ValidateIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateIDResponse.Merge(m, src)
}
func (m *ValidateIDResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateIDResponse.Size(m)
}
func (m *ValidateIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateIDResponse proto.InternalMessageInfo

func (m *ValidateIDResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type AuthenticationRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{6}
}

func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type AuthenticationResponse struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResponse) Reset()         { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()    {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{7}
}

func (m *AuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResponse.Unmarshal(m, b)
}
func (m *AuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResponse.Merge(m, src)
}
func (m *AuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResponse.Size(m)
}
func (m *AuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResponse proto.InternalMessageInfo

func (m *AuthenticationResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterClientRequest)(nil), "RegisterClientRequest")
	proto.RegisterType((*RegisterClientResponse)(nil), "RegisterClientResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*ValidateIDRequest)(nil), "ValidateIDRequest")
	proto.RegisterType((*ValidateIDResponse)(nil), "ValidateIDResponse")
	proto.RegisterType((*AuthenticationRequest)(nil), "AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "AuthenticationResponse")
}

func init() { proto.RegisterFile("clients.proto", fileDescriptor_6c7b36ecb5ad4a28) }

var fileDescriptor_6c7b36ecb5ad4a28 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0xc7, 0x49, 0xa1, 0xbd, 0xed, 0xb9, 0xcd, 0x85, 0xce, 0x6d, 0xd3, 0xdc, 0x50, 0xb8, 0x32,
	0x2b, 0xe9, 0x62, 0x06, 0xfc, 0x58, 0xd8, 0x9d, 0x58, 0x84, 0x82, 0xa0, 0x06, 0x29, 0x74, 0x19,
	0xdb, 0x31, 0x0e, 0x86, 0x99, 0x9a, 0x99, 0xea, 0xde, 0x57, 0xf0, 0xcd, 0xf4, 0x15, 0x7c, 0x10,
	0xc9, 0x64, 0xda, 0xa6, 0x1f, 0x16, 0xc1, 0xe5, 0xf9, 0xfa, 0x9d, 0x93, 0xff, 0x7f, 0x02, 0xee,
	0x38, 0xe1, 0x4c, 0x68, 0x45, 0xa6, 0xa9, 0xd4, 0x32, 0xe8, 0xc4, 0x52, 0xc6, 0x09, 0xa3, 0xd1,
	0x94, 0xd3, 0x48, 0x08, 0xa9, 0x23, 0xcd, 0xa5, 0xb0, 0x55, 0x7c, 0x09, 0xad, 0x90, 0xc5, 0x5c,
	0x69, 0x96, 0x9e, 0x99, 0xb1, 0x90, 0x3d, 0xce, 0x98, 0xd2, 0x28, 0x80, 0x6a, 0x9e, 0x18, 0xf4,
	0x7d, 0x67, 0xcf, 0xd9, 0xaf, 0x85, 0x8b, 0x38, 0xab, 0x5d, 0x45, 0x4a, 0x3d, 0xcb, 0x74, 0xe2,
	0x97, 0xf2, 0xda, 0x3c, 0xc6, 0x3e, 0x78, 0xeb, 0x40, 0x35, 0x95, 0x42, 0x31, 0x7c, 0x0e, 0xf5,
	0x0b, 0x19, 0x73, 0xf1, 0xd3, 0x0d, 0xd7, 0xe0, 0x5a, 0x4e, 0x0e, 0x46, 0x1d, 0xa8, 0x9d, 0xce,
	0xf4, 0xfd, 0x8d, 0x7c, 0x60, 0xc2, 0x92, 0x96, 0x09, 0x84, 0xa1, 0x1e, 0xb2, 0xbb, 0x94, 0x29,
	0xdb, 0x90, 0xe3, 0x56, 0x72, 0x98, 0x42, 0x63, 0x18, 0x25, 0x7c, 0x12, 0x69, 0x36, 0xe8, 0x7f,
	0xe3, 0x3e, 0xdc, 0x05, 0x54, 0x1c, 0xb0, 0x87, 0x34, 0xa1, 0x6c, 0xb2, 0xa6, 0xbd, 0x1a, 0xe6,
	0x01, 0x3e, 0x86, 0x56, 0x76, 0x0d, 0x13, 0x9a, 0x8f, 0x8d, 0xf6, 0xf3, 0x05, 0x3b, 0xef, 0xc6,
	0x47, 0xe0, 0xad, 0x8f, 0xd9, 0x35, 0x3b, 0x0e, 0x3b, 0x78, 0x2b, 0xc1, 0xaf, 0x3c, 0x50, 0x68,
	0x04, 0xd5, 0xb9, 0x15, 0xc8, 0x23, 0x5b, 0x6d, 0x0e, 0xda, 0xe4, 0x0b, 0xb7, 0x3a, 0x2f, 0xef,
	0x1f, 0xaf, 0x25, 0x0f, 0x37, 0xa8, 0x7d, 0x4e, 0x34, 0xb5, 0x8d, 0x3d, 0xa7, 0x8b, 0x86, 0x00,
	0xcb, 0xef, 0x47, 0x88, 0x6c, 0xa8, 0x17, 0xfc, 0x25, 0x9b, 0x02, 0xe1, 0xff, 0x06, 0xfa, 0x0f,
	0x37, 0x17, 0x50, 0x3e, 0xa1, 0x4f, 0xb6, 0x2f, 0xe3, 0x9e, 0x40, 0xd9, 0x78, 0x8b, 0x5c, 0x52,
	0x7c, 0x2b, 0xc1, 0x1f, 0xb2, 0x62, 0x39, 0x6e, 0x18, 0xd0, 0x6f, 0x5c, 0xa1, 0x49, 0x96, 0xcf,
	0x46, 0x47, 0x50, 0x2f, 0xe8, 0xc5, 0x90, 0x47, 0xb6, 0xaa, 0x1e, 0xb4, 0xc9, 0x76, 0x59, 0xb1,
	0x6f, 0x98, 0x08, 0xbb, 0x34, 0x2a, 0x70, 0x7a, 0x4e, 0xf7, 0xb6, 0x62, 0xfe, 0x95, 0xc3, 0xcf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x04, 0xb6, 0x5e, 0x5a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientsClient is the client API for Clients service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientsClient interface {
	Register(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error)
	ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
}

type clientsClient struct {
	cc *grpc.ClientConn
}

func NewClientsClient(cc *grpc.ClientConn) ClientsClient {
	return &clientsClient{cc}
}

func (c *clientsClient) Register(ctx context.Context, in *RegisterClientRequest, opts ...grpc.CallOption) (*RegisterClientResponse, error) {
	out := new(RegisterClientResponse)
	err := c.cc.Invoke(ctx, "/Clients/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error) {
	out := new(ValidateIDResponse)
	err := c.cc.Invoke(ctx, "/Clients/ValidateID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Clients/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, "/Clients/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServer is the server API for Clients service.
type ClientsServer interface {
	Register(context.Context, *RegisterClientRequest) (*RegisterClientResponse, error)
	ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
}

func RegisterClientsServer(s *grpc.Server, srv ClientsServer) {
	s.RegisterService(&_Clients_serviceDesc, srv)
}

func _Clients_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Register(ctx, req.(*RegisterClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_ValidateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).ValidateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/ValidateID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).ValidateID(ctx, req.(*ValidateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Authenticate(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clients_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Clients",
	HandlerType: (*ClientsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Clients_Register_Handler,
		},
		{
			MethodName: "ValidateID",
			Handler:    _Clients_ValidateID_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Clients_Login_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Clients_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
