// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clients.proto

package contract

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateClientRequest struct {
	ClientType           string   `protobuf:"bytes,1,opt,name=ClientType,proto3" json:"ClientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientRequest) Reset()         { *m = CreateClientRequest{} }
func (m *CreateClientRequest) String() string { return proto.CompactTextString(m) }
func (*CreateClientRequest) ProtoMessage()    {}
func (*CreateClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{0}
}

func (m *CreateClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientRequest.Unmarshal(m, b)
}
func (m *CreateClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientRequest.Marshal(b, m, deterministic)
}
func (m *CreateClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientRequest.Merge(m, src)
}
func (m *CreateClientRequest) XXX_Size() int {
	return xxx_messageInfo_CreateClientRequest.Size(m)
}
func (m *CreateClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientRequest proto.InternalMessageInfo

func (m *CreateClientRequest) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type CreateClientResponse struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateClientResponse) Reset()         { *m = CreateClientResponse{} }
func (m *CreateClientResponse) String() string { return proto.CompactTextString(m) }
func (*CreateClientResponse) ProtoMessage()    {}
func (*CreateClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{1}
}

func (m *CreateClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateClientResponse.Unmarshal(m, b)
}
func (m *CreateClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateClientResponse.Marshal(b, m, deterministic)
}
func (m *CreateClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateClientResponse.Merge(m, src)
}
func (m *CreateClientResponse) XXX_Size() int {
	return xxx_messageInfo_CreateClientResponse.Size(m)
}
func (m *CreateClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateClientResponse proto.InternalMessageInfo

func (m *CreateClientResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type RetrieveClientRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveClientRequest) Reset()         { *m = RetrieveClientRequest{} }
func (m *RetrieveClientRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveClientRequest) ProtoMessage()    {}
func (*RetrieveClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{2}
}

func (m *RetrieveClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveClientRequest.Unmarshal(m, b)
}
func (m *RetrieveClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveClientRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveClientRequest.Merge(m, src)
}
func (m *RetrieveClientRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveClientRequest.Size(m)
}
func (m *RetrieveClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveClientRequest proto.InternalMessageInfo

func (m *RetrieveClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type RetrieveClientResponse struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	ClientType           string   `protobuf:"bytes,2,opt,name=ClientType,proto3" json:"ClientType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveClientResponse) Reset()         { *m = RetrieveClientResponse{} }
func (m *RetrieveClientResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveClientResponse) ProtoMessage()    {}
func (*RetrieveClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{3}
}

func (m *RetrieveClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveClientResponse.Unmarshal(m, b)
}
func (m *RetrieveClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveClientResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveClientResponse.Merge(m, src)
}
func (m *RetrieveClientResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveClientResponse.Size(m)
}
func (m *RetrieveClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveClientResponse proto.InternalMessageInfo

func (m *RetrieveClientResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *RetrieveClientResponse) GetClientType() string {
	if m != nil {
		return m.ClientType
	}
	return ""
}

type DeleteClientRequest struct {
	ClientID             string   `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientRequest) Reset()         { *m = DeleteClientRequest{} }
func (m *DeleteClientRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteClientRequest) ProtoMessage()    {}
func (*DeleteClientRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{4}
}

func (m *DeleteClientRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientRequest.Unmarshal(m, b)
}
func (m *DeleteClientRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientRequest.Marshal(b, m, deterministic)
}
func (m *DeleteClientRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientRequest.Merge(m, src)
}
func (m *DeleteClientRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteClientRequest.Size(m)
}
func (m *DeleteClientRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientRequest proto.InternalMessageInfo

func (m *DeleteClientRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type DeleteClientResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteClientResponse) Reset()         { *m = DeleteClientResponse{} }
func (m *DeleteClientResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteClientResponse) ProtoMessage()    {}
func (*DeleteClientResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c7b36ecb5ad4a28, []int{5}
}

func (m *DeleteClientResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteClientResponse.Unmarshal(m, b)
}
func (m *DeleteClientResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteClientResponse.Marshal(b, m, deterministic)
}
func (m *DeleteClientResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteClientResponse.Merge(m, src)
}
func (m *DeleteClientResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteClientResponse.Size(m)
}
func (m *DeleteClientResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteClientResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteClientResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateClientRequest)(nil), "CreateClientRequest")
	proto.RegisterType((*CreateClientResponse)(nil), "CreateClientResponse")
	proto.RegisterType((*RetrieveClientRequest)(nil), "RetrieveClientRequest")
	proto.RegisterType((*RetrieveClientResponse)(nil), "RetrieveClientResponse")
	proto.RegisterType((*DeleteClientRequest)(nil), "DeleteClientRequest")
	proto.RegisterType((*DeleteClientResponse)(nil), "DeleteClientResponse")
}

func init() { proto.RegisterFile("clients.proto", fileDescriptor_6c7b36ecb5ad4a28) }

var fileDescriptor_6c7b36ecb5ad4a28 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xc9, 0x4c,
	0xcd, 0x2b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf,
	0x83, 0xca, 0x2a, 0x99, 0x72, 0x09, 0x3b, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0x3a, 0x83, 0x35, 0x05,
	0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x71, 0x71, 0x41, 0x04, 0x42, 0x2a, 0x0b, 0x52,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x94, 0x8c, 0xb8, 0x44, 0x50, 0xb5, 0x15,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x49, 0x71, 0x71, 0x40, 0x44, 0x3c, 0x5d, 0xa0, 0xba, 0xe0,
	0x7c, 0x25, 0x63, 0x2e, 0xd1, 0xa0, 0xd4, 0x92, 0xa2, 0xcc, 0xd4, 0x32, 0x34, 0xcb, 0xf0, 0x69,
	0x0a, 0xe1, 0x12, 0x43, 0xd7, 0x44, 0xd8, 0x2a, 0x34, 0xe7, 0x33, 0x61, 0x38, 0xdf, 0x90, 0x4b,
	0xd8, 0x25, 0x35, 0x27, 0xb5, 0x84, 0x04, 0x87, 0x88, 0x71, 0x89, 0xa0, 0x6a, 0x81, 0x38, 0xc3,
	0xa8, 0x99, 0x89, 0x8b, 0x1d, 0x22, 0x54, 0x2c, 0xe4, 0xc5, 0xc5, 0x06, 0x09, 0x15, 0x21, 0x11,
	0x3d, 0x2c, 0xa1, 0x2a, 0x25, 0xaa, 0x87, 0x2d, 0xd0, 0x94, 0x84, 0x9b, 0x2e, 0x3f, 0x99, 0xcc,
	0xc4, 0xab, 0xc4, 0xa1, 0x0f, 0x8d, 0x39, 0x2b, 0x46, 0x2d, 0xa1, 0x08, 0x2e, 0x0e, 0x98, 0xc7,
	0x85, 0xc4, 0xf4, 0xb0, 0x06, 0x9c, 0x94, 0xb8, 0x1e, 0xf6, 0xb0, 0x51, 0x92, 0x06, 0x9b, 0x28,
	0x2a, 0x24, 0x0c, 0x33, 0x51, 0xbf, 0x1a, 0xe6, 0x91, 0x5a, 0xa1, 0x20, 0x2e, 0x36, 0x88, 0x4f,
	0x84, 0x44, 0xf4, 0xb0, 0x84, 0x82, 0x94, 0xa8, 0x1e, 0x36, 0x8f, 0xc2, 0xcc, 0xd4, 0xc2, 0x66,
	0x66, 0x12, 0x1b, 0x38, 0x35, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x4a, 0x73, 0xc0,
	0x7c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientsClient is the client API for Clients service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientsClient interface {
	Create(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error)
	Retrieve(ctx context.Context, in *RetrieveClientRequest, opts ...grpc.CallOption) (*RetrieveClientResponse, error)
	Delete(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error)
}

type clientsClient struct {
	cc *grpc.ClientConn
}

func NewClientsClient(cc *grpc.ClientConn) ClientsClient {
	return &clientsClient{cc}
}

func (c *clientsClient) Create(ctx context.Context, in *CreateClientRequest, opts ...grpc.CallOption) (*CreateClientResponse, error) {
	out := new(CreateClientResponse)
	err := c.cc.Invoke(ctx, "/Clients/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) Retrieve(ctx context.Context, in *RetrieveClientRequest, opts ...grpc.CallOption) (*RetrieveClientResponse, error) {
	out := new(RetrieveClientResponse)
	err := c.cc.Invoke(ctx, "/Clients/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientsClient) Delete(ctx context.Context, in *DeleteClientRequest, opts ...grpc.CallOption) (*DeleteClientResponse, error) {
	out := new(DeleteClientResponse)
	err := c.cc.Invoke(ctx, "/Clients/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientsServer is the server API for Clients service.
type ClientsServer interface {
	Create(context.Context, *CreateClientRequest) (*CreateClientResponse, error)
	Retrieve(context.Context, *RetrieveClientRequest) (*RetrieveClientResponse, error)
	Delete(context.Context, *DeleteClientRequest) (*DeleteClientResponse, error)
}

func RegisterClientsServer(s *grpc.Server, srv ClientsServer) {
	s.RegisterService(&_Clients_serviceDesc, srv)
}

func _Clients_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Create(ctx, req.(*CreateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Retrieve(ctx, req.(*RetrieveClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clients_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clients/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientsServer).Delete(ctx, req.(*DeleteClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clients_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Clients",
	HandlerType: (*ClientsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Clients_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _Clients_Retrieve_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Clients_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clients.proto",
}
