// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package contract

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterUserRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserRequest) Reset()         { *m = RegisterUserRequest{} }
func (m *RegisterUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUserRequest) ProtoMessage()    {}
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{0}
}

func (m *RegisterUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserRequest.Unmarshal(m, b)
}
func (m *RegisterUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserRequest.Marshal(b, m, deterministic)
}
func (m *RegisterUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserRequest.Merge(m, src)
}
func (m *RegisterUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterUserRequest.Size(m)
}
func (m *RegisterUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserRequest proto.InternalMessageInfo

func (m *RegisterUserRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *RegisterUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUserResponse) Reset()         { *m = RegisterUserResponse{} }
func (m *RegisterUserResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterUserResponse) ProtoMessage()    {}
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{1}
}

func (m *RegisterUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUserResponse.Unmarshal(m, b)
}
func (m *RegisterUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUserResponse.Marshal(b, m, deterministic)
}
func (m *RegisterUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUserResponse.Merge(m, src)
}
func (m *RegisterUserResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterUserResponse.Size(m)
}
func (m *RegisterUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUserResponse proto.InternalMessageInfo

type LoginRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

func (m *LoginResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type ValidateIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateIDRequest) Reset()         { *m = ValidateIDRequest{} }
func (m *ValidateIDRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateIDRequest) ProtoMessage()    {}
func (*ValidateIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{4}
}

func (m *ValidateIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateIDRequest.Unmarshal(m, b)
}
func (m *ValidateIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateIDRequest.Marshal(b, m, deterministic)
}
func (m *ValidateIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateIDRequest.Merge(m, src)
}
func (m *ValidateIDRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateIDRequest.Size(m)
}
func (m *ValidateIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateIDRequest proto.InternalMessageInfo

func (m *ValidateIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ValidateIDResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=Valid,proto3" json:"Valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateIDResponse) Reset()         { *m = ValidateIDResponse{} }
func (m *ValidateIDResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateIDResponse) ProtoMessage()    {}
func (*ValidateIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{5}
}

func (m *ValidateIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateIDResponse.Unmarshal(m, b)
}
func (m *ValidateIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateIDResponse.Marshal(b, m, deterministic)
}
func (m *ValidateIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateIDResponse.Merge(m, src)
}
func (m *ValidateIDResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateIDResponse.Size(m)
}
func (m *ValidateIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateIDResponse proto.InternalMessageInfo

func (m *ValidateIDResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type AuthenticationRequest struct {
	AuthToken            string   `protobuf:"bytes,1,opt,name=AuthToken,proto3" json:"AuthToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationRequest) Reset()         { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()    {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{6}
}

func (m *AuthenticationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationRequest.Unmarshal(m, b)
}
func (m *AuthenticationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationRequest.Merge(m, src)
}
func (m *AuthenticationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticationRequest.Size(m)
}
func (m *AuthenticationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationRequest proto.InternalMessageInfo

func (m *AuthenticationRequest) GetAuthToken() string {
	if m != nil {
		return m.AuthToken
	}
	return ""
}

type AuthenticationResponse struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticationResponse) Reset()         { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()    {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_030765f334c86cea, []int{7}
}

func (m *AuthenticationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticationResponse.Unmarshal(m, b)
}
func (m *AuthenticationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticationResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticationResponse.Merge(m, src)
}
func (m *AuthenticationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticationResponse.Size(m)
}
func (m *AuthenticationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticationResponse proto.InternalMessageInfo

func (m *AuthenticationResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticationResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterUserRequest)(nil), "RegisterUserRequest")
	proto.RegisterType((*RegisterUserResponse)(nil), "RegisterUserResponse")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*ValidateIDRequest)(nil), "ValidateIDRequest")
	proto.RegisterType((*ValidateIDResponse)(nil), "ValidateIDResponse")
	proto.RegisterType((*AuthenticationRequest)(nil), "AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "AuthenticationResponse")
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_030765f334c86cea) }

var fileDescriptor_030765f334c86cea = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x8e, 0x12, 0x31,
	0x1c, 0xc6, 0x33, 0x24, 0x90, 0xe1, 0x0f, 0x68, 0x28, 0xc3, 0x40, 0x1a, 0x4c, 0x4c, 0x4f, 0x06,
	0x93, 0x4e, 0xa2, 0xf1, 0x20, 0x37, 0x0d, 0x1e, 0x30, 0x1e, 0x74, 0x44, 0x13, 0x8f, 0x55, 0xea,
	0xd8, 0x38, 0xb4, 0xec, 0xb4, 0xec, 0xde, 0xf7, 0x15, 0xf6, 0xa5, 0xf6, 0xbe, 0xaf, 0xb0, 0x0f,
	0xb2, 0x69, 0xa7, 0xc0, 0xb0, 0x4c, 0x76, 0x0f, 0x7b, 0xfc, 0xff, 0xfb, 0xf5, 0xc7, 0xc7, 0xf7,
	0x75, 0xa0, 0xb3, 0xd5, 0xbc, 0xd0, 0x74, 0x53, 0x28, 0xa3, 0xf0, 0x24, 0x53, 0x2a, 0xcb, 0x79,
	0xc2, 0x36, 0x22, 0x61, 0x52, 0x2a, 0xc3, 0x8c, 0x50, 0xd2, 0x9f, 0x92, 0x05, 0x0c, 0x52, 0x9e,
	0x09, 0x6d, 0x78, 0xf1, 0x43, 0xf3, 0x22, 0xe5, 0x67, 0x5b, 0xae, 0x0d, 0x8a, 0xa1, 0x65, 0xc7,
	0xc5, 0x7c, 0x1c, 0xbc, 0x0c, 0x5e, 0xb5, 0x53, 0x3f, 0x21, 0x0c, 0xe1, 0x57, 0xa6, 0xf5, 0x85,
	0x2a, 0x56, 0xe3, 0x86, 0x3b, 0xd9, 0xcf, 0x24, 0x86, 0xe8, 0x18, 0xa5, 0x37, 0x4a, 0x6a, 0x4e,
	0x3e, 0x42, 0xf7, 0x8b, 0xca, 0x84, 0x7c, 0x0a, 0xfb, 0x1b, 0xf4, 0x3c, 0xa3, 0x84, 0xa2, 0x09,
	0xb4, 0x3f, 0x6c, 0xcd, 0xbf, 0xa5, 0xfa, 0xcf, 0xa5, 0xe7, 0x1c, 0x16, 0x88, 0x40, 0x37, 0xe5,
	0x7f, 0x0b, 0xae, 0xbd, 0xa0, 0xc4, 0x1d, 0xed, 0xc8, 0x6b, 0xe8, 0xff, 0x64, 0xb9, 0x58, 0x31,
	0xc3, 0x17, 0xf3, 0x47, 0xbc, 0x91, 0x29, 0xa0, 0xaa, 0xd8, 0x9b, 0x88, 0xa0, 0xe9, 0xb6, 0x4e,
	0x1c, 0xa6, 0xe5, 0x40, 0xde, 0xc1, 0xd0, 0x3a, 0xe1, 0xd2, 0x88, 0x3f, 0x2e, 0xeb, 0x1d, 0xfc,
	0x41, 0xcf, 0xe4, 0x33, 0xc4, 0xf7, 0xaf, 0xf9, 0x9f, 0xc1, 0x10, 0x5a, 0x1b, 0x92, 0xad, 0xb9,
	0xbf, 0xb6, 0x9f, 0xad, 0x85, 0x4f, 0x6b, 0x26, 0x72, 0xff, 0x17, 0xcb, 0xe1, 0xcd, 0x75, 0x03,
	0x9a, 0x56, 0xa2, 0xd1, 0x77, 0x08, 0x77, 0xa5, 0xa0, 0x88, 0xd6, 0x54, 0x8d, 0x87, 0xb4, 0xb6,
	0x35, 0x7c, 0x79, 0x73, 0x7b, 0xd5, 0x88, 0xc8, 0xf3, 0xc4, 0x3d, 0xa6, 0xa4, 0xf0, 0xa2, 0x59,
	0x30, 0x45, 0x4b, 0x80, 0x43, 0x1a, 0x08, 0xd1, 0x93, 0x1c, 0xf1, 0x80, 0x9e, 0xc6, 0x45, 0x5e,
	0x38, 0xe4, 0x88, 0x20, 0x8f, 0x14, 0xab, 0xe4, 0xdc, 0xab, 0x2c, 0xf5, 0x3d, 0x34, 0x5d, 0xc7,
	0xa8, 0x47, 0xab, 0xef, 0x05, 0x3f, 0xa3, 0x47, 0xd5, 0x93, 0xbe, 0xc3, 0x74, 0x48, 0x2b, 0xc9,
	0xed, 0xde, 0x5e, 0xfd, 0x05, 0xdd, 0x4a, 0x76, 0x1c, 0xc5, 0xb4, 0xb6, 0x01, 0x3c, 0xa2, 0xf5,
	0x11, 0x93, 0xb1, 0x63, 0x22, 0xd2, 0x4b, 0x58, 0x85, 0x33, 0x0b, 0xa6, 0xbf, 0x5b, 0xee, 0x3b,
	0x79, 0x7b, 0x17, 0x00, 0x00, 0xff, 0xff, 0x67, 0xab, 0x7f, 0xa8, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Register(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, "/Users/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) ValidateID(ctx context.Context, in *ValidateIDRequest, opts ...grpc.CallOption) (*ValidateIDResponse, error) {
	out := new(ValidateIDResponse)
	err := c.cc.Invoke(ctx, "/Users/ValidateID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/Users/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := c.cc.Invoke(ctx, "/Users/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Register(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	ValidateID(context.Context, *ValidateIDRequest) (*ValidateIDResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Register(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_ValidateID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).ValidateID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/ValidateID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).ValidateID(ctx, req.(*ValidateIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Users/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Authenticate(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Users_Register_Handler,
		},
		{
			MethodName: "ValidateID",
			Handler:    _Users_ValidateID_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Users_Login_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Users_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}
